version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: drizzle
      POSTGRES_DB: local_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drizzle -d local_db"]
      interval: 5s
      timeout: 5s
      retries: 5
