name: Seed Database

on:
  schedule:
    - cron: "0 6-13 * * 1-5" # Runs hourly Mon-Fri 8am-3pm Polish time (UTC+2)
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Trigger database seed
        run: |
          curl -X POST ${{ secrets.VERCEL_URL }}/api/seed \
          -H "Authorization: Bearer ${{ secrets.SEED_SECRET }}"
