name: Seed Database

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger database seed
        run: |
          curl -X POST https://llhurt.com/api/seed \
          -H "Authorization: Bearer ${{ secrets.SEED_SECRET }}"
